config/routes.rb
Portfolio::Application.routes.draw do
  
  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"
  
  namespace :api do
    namespace :v1 do
      resources :posts, :only => [ :create ]
    end
  end
  
  devise_for :users,
    controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :posts do
    resources :comments
  end

  resources :projects do
    resources :comments
  end

  resources :comments

  get "welcome/index"

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true

  validates :content, presence: true
  validates :author_email, presence: true
  validates :author, presence: true
end

app/controllers/comments_controller.rb
# Comments are short messages about blog posts
class CommentsController < ApplicationController
  before_filter :load_commentable, except: [:index]

  def index
    authorize Comment
    @comments = Comment.all
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "Comment is awaiting moderation"
      redirect_to @commentable
      CommentMailer.delay.new_comment(@comment, @commentable)
    else
      instance_variable_set("@#{@resource.singularize}".to_sym, @commentable)
      render template: "#{@resource}/show"
    end
  end

  def update
    if @commentable.class == Comment
      @comment_thing = @commentable
    else
      @comment_thing = @commentable.comment
    end

    if @comment_thing.update_attributes(comment_params)
      flash[:notice] = "Comment has been updated"
      if @comment_thing.class == Comment
        redirect_to comments_path
      else
        redirect_to @commentable
      end
    else
      instance_variable_set("@#{@resource.singularize}".to_sym, @commentable)
      render template: "#{@resource}/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:author,
                                    :author_url,
                                    :author_email,
                                    :content,
                                    :referrer,
                                    :approved,
                                    :commentable_id)
  end

  def load_commentable
    @resource, id = request.path.split('/')[1, 2]
    @commentable = @resource.singularize.classify.constantize.find(id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% if comment.approved? %>
<div class="comment">
  <p><%= comment.author %> said:</p>
  <p><%= comment.content %></p>
</div>
<% end %>

app/views/comments/_form.html.erb
<div class="comment_form">
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for [@commentable, @comment] do |f| %>
    <div class="field">
      <%= f.label :author, "Your name" %>
      <%= f.text_field :author %>
    </div>
    <div class="field">
      <%= f.label :author_email, "Your email" %>
      <%= f.text_field :author_email %>
    </div>
    <div class="field">
      <%= f.label :author_url, "Your URL" %>
      <%= f.text_field :author_url %>
    </div>
    <div class="field">
      <%= f.label :content, "Your Comment" %>
      <%= f.text_field :content %>
    </div>
    <%= f.hidden_field :referrer, value: request.referrer %>
    <%= f.hidden_field :commentable_id,  value: @commentable.id %>
    <div class="actions">
      <%= f.submit "Submit comment for approval" %>
    <div>
  <% end %>
</div><!-- .comment_form -->

app/views/comments/index.html.erb
<h2>Admin comments</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Author</th>
      <th>URL</th>
      <th>Email</th>
      <th>Referrer</th>
      <th>Approved</th>
    </tr>
  </thead>
  <% @comments.each do |comment| %>
    <tr <%= raw 'class="warning"' unless comment.approved? %> id="<%= dom_id(comment) %>">
      <td><%= comment.author%></td>
      <td><%= comment.author_url %></td>
      <td><%= comment.author_email %></td>
      <td><%= comment.referrer %></td>
      <td><%= link_to 'Edit', edit_comment_path(comment), class: "btn btn-info" %></td>
      <td>
        <% if comment.approved? %>
          Approved
        <% else %>
          <%= button_to 'Approve',
            comment_path(comment, comment: { approved: true }),
            method: :put, class: "btn btn-warning" %>
        <% end %>
      </td>
      <td>
        <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } ,
        class: "btn btn-danger" %>
      </td>
    </tr>
    <tr>
      <td class="comment_content" colspan="7"><%= comment.content %></td>
    </tr>
    <% end %>
</table>